#if !canImport(ObjectiveC)
import XCTest

extension AnyHeaderFieldDelegateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnyHeaderFieldDelegateTests = [
        ("test_initializer", test_initializer),
    ]
}

extension CacheControlDirectiveTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CacheControlDirectiveTests = [
        ("test_header", test_header),
        ("test_set", test_set),
    ]
}

extension ContentDispositionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContentDispositionTests = [
        ("test_parser", test_parser),
    ]
}

extension CookieTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CookieTests = [
        ("test_date", test_date),
        ("test_requestHeader", test_requestHeader),
        ("test_responseHeader", test_responseHeader),
        ("test_setCookieHeaderField", test_setCookieHeaderField),
    ]
}

extension ETagTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ETagTests = [
        ("test_comparison", test_comparison),
        ("test_headerField", test_headerField),
        ("test_initialization", test_initialization),
        ("test_list", test_list),
    ]
}

extension HeaderFieldTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HeaderFieldTests = [
        ("test_contentLengh", test_contentLengh),
        ("test_delegateSelection", test_delegateSelection),
        ("test_initialization", test_initialization),
        ("test_name_initialization", test_name_initialization),
        ("test_value_initialization", test_value_initialization),
    ]
}

extension HeaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HeaderTests = [
        ("test_appending", test_appending),
    ]
}

extension LastModifiedHeaderFieldDelegateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LastModifiedHeaderFieldDelegateTests = [
        ("test_initializer", test_initializer),
    ]
}

extension MIMETypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MIMETypeTests = [
        ("test_parser", test_parser),
        ("test_pathExtensions", test_pathExtensions),
    ]
}

extension QuotedStringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QuotedStringTests = [
        ("test_quote", test_quote),
        ("test_unquote", test_unquote),
    ]
}

extension TokenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TokenTests = [
        ("test_dictionary", test_dictionary),
        ("test_split", test_split),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AnyHeaderFieldDelegateTests.__allTests__AnyHeaderFieldDelegateTests),
        testCase(CacheControlDirectiveTests.__allTests__CacheControlDirectiveTests),
        testCase(ContentDispositionTests.__allTests__ContentDispositionTests),
        testCase(CookieTests.__allTests__CookieTests),
        testCase(ETagTests.__allTests__ETagTests),
        testCase(HeaderFieldTests.__allTests__HeaderFieldTests),
        testCase(HeaderTests.__allTests__HeaderTests),
        testCase(LastModifiedHeaderFieldDelegateTests.__allTests__LastModifiedHeaderFieldDelegateTests),
        testCase(MIMETypeTests.__allTests__MIMETypeTests),
        testCase(QuotedStringTests.__allTests__QuotedStringTests),
        testCase(TokenTests.__allTests__TokenTests),
    ]
}
#endif
