#if !canImport(ObjectiveC)
import XCTest

extension AnyHTTPHeaderFieldDelegateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnyHTTPHeaderFieldDelegateTests = [
        ("test_initializer", test_initializer),
    ]
}

extension CacheControlDirectiveTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CacheControlDirectiveTests = [
        ("test_header", test_header),
        ("test_set", test_set),
    ]
}

extension ContentDispositionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContentDispositionTests = [
        ("test_parser", test_parser),
    ]
}

extension HTTPCookieTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTTPCookieTests = [
        ("test_date", test_date),
        ("test_requestHeader", test_requestHeader),
        ("test_responseHeader", test_responseHeader),
        ("test_setCookieHeaderField", test_setCookieHeaderField),
    ]
}

extension HTTPETagTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTTPETagTests = [
        ("test_comparison", test_comparison),
        ("test_headerField", test_headerField),
        ("test_initialization", test_initialization),
        ("test_list", test_list),
    ]
}

extension HTTPHeaderFieldNameTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTTPHeaderFieldNameTests = [
        ("test_caseInsensitivity", test_caseInsensitivity),
    ]
}

extension HTTPHeaderFieldTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTTPHeaderFieldTests = [
        ("test_contentLengh", test_contentLengh),
        ("test_delegateSelection", test_delegateSelection),
        ("test_initialization", test_initialization),
        ("test_name_initialization", test_name_initialization),
        ("test_value_initialization", test_value_initialization),
    ]
}

extension HTTPHeaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTTPHeaderTests = [
        ("test_appending", test_appending),
        ("test_asSequence", test_asSequence),
    ]
}

extension LastModifiedHTTPHeaderFieldDelegateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LastModifiedHTTPHeaderFieldDelegateTests = [
        ("test_value", test_value),
    ]
}

extension MIMETypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MIMETypeTests = [
        ("test_parser", test_parser),
        ("test_pathExtensions", test_pathExtensions),
    ]
}

extension QuotedStringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QuotedStringTests = [
        ("test_quote", test_quote),
        ("test_unquote", test_unquote),
    ]
}

extension TokenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TokenTests = [
        ("test_dictionary", test_dictionary),
        ("test_split", test_split),
    ]
}

extension URLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLTests = [
        ("test_content", test_content),
        ("test_eTag", test_eTag),
        ("test_lastModified", test_lastModified),
        ("test_postRequest", test_postRequest),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AnyHTTPHeaderFieldDelegateTests.__allTests__AnyHTTPHeaderFieldDelegateTests),
        testCase(CacheControlDirectiveTests.__allTests__CacheControlDirectiveTests),
        testCase(ContentDispositionTests.__allTests__ContentDispositionTests),
        testCase(HTTPCookieTests.__allTests__HTTPCookieTests),
        testCase(HTTPETagTests.__allTests__HTTPETagTests),
        testCase(HTTPHeaderFieldNameTests.__allTests__HTTPHeaderFieldNameTests),
        testCase(HTTPHeaderFieldTests.__allTests__HTTPHeaderFieldTests),
        testCase(HTTPHeaderTests.__allTests__HTTPHeaderTests),
        testCase(LastModifiedHTTPHeaderFieldDelegateTests.__allTests__LastModifiedHTTPHeaderFieldDelegateTests),
        testCase(MIMETypeTests.__allTests__MIMETypeTests),
        testCase(QuotedStringTests.__allTests__QuotedStringTests),
        testCase(TokenTests.__allTests__TokenTests),
        testCase(URLTests.__allTests__URLTests),
    ]
}
#endif
