//# DO NOT MODIFY.
//# This is autogenerated by `ySwiftCodeUpdater`(https://github.com/YOCKOW/ySwiftCodeUpdater).
//# Please see documents in this project to learn how to regenerate.
//# The material(s) to generate this file was/were obtained from below:
//
// URL: https://www.iana.org/assignments/cont-disp/cont-disp-2.csv
// Last-Modified: 2021-04-15T19:20:41Z

extension ContentDispositionParameterKey {
  public static let filename = ContentDispositionParameterKey(rawValue: "filename")
  public static let creationDate = ContentDispositionParameterKey(rawValue: "creation-date")
  public static let modificationDate = ContentDispositionParameterKey(rawValue: "modification-date")
  public static let readDate = ContentDispositionParameterKey(rawValue: "read-date")
  public static let size = ContentDispositionParameterKey(rawValue: "size")
  public static let name = ContentDispositionParameterKey(rawValue: "name")
  public static let voice = ContentDispositionParameterKey(rawValue: "voice")
  public static let handling = ContentDispositionParameterKey(rawValue: "handling")
  public static let previewType = ContentDispositionParameterKey(rawValue: "preview-type")
  public static let reaction = ContentDispositionParameterKey(rawValue: "reaction")
}
