//# DO NOT MODIFY.
//# This is autogenerated by `ySwiftCodeUpdater`(https://github.com/YOCKOW/ySwiftCodeUpdater).
//# Please see documents in this project to learn how to regenerate.
//# The material(s) to generate this file was/were obtained from below:
//
// URL: https://www.iana.org/assignments/cont-disp/cont-disp-2.csv
// Last-Modified: 2025-10-24T07:01:26Z

extension HTTPHeaderFieldParameter.Name {
  public static let filename = HTTPHeaderFieldParameter.Name(_validatedAttribute: "filename", sectionIndex: nil)
  public static let creationDate = HTTPHeaderFieldParameter.Name(_validatedAttribute: "creation-date", sectionIndex: nil)
  public static let modificationDate = HTTPHeaderFieldParameter.Name(_validatedAttribute: "modification-date", sectionIndex: nil)
  public static let readDate = HTTPHeaderFieldParameter.Name(_validatedAttribute: "read-date", sectionIndex: nil)
  public static let size = HTTPHeaderFieldParameter.Name(_validatedAttribute: "size", sectionIndex: nil)
  public static let name = HTTPHeaderFieldParameter.Name(_validatedAttribute: "name", sectionIndex: nil)
  public static let voice = HTTPHeaderFieldParameter.Name(_validatedAttribute: "voice", sectionIndex: nil)
  public static let handling = HTTPHeaderFieldParameter.Name(_validatedAttribute: "handling", sectionIndex: nil)
  public static let previewType = HTTPHeaderFieldParameter.Name(_validatedAttribute: "preview-type", sectionIndex: nil)
  public static let reaction = HTTPHeaderFieldParameter.Name(_validatedAttribute: "reaction", sectionIndex: nil)
}
