//# DO NOT MODIFY.
//# This is autogenerated by `ySwiftCodeUpdater`(https://github.com/YOCKOW/ySwiftCodeUpdater).
//# Please see documents in this project to learn how to regenerate.
//# The material(s) to generate this file was/were obtained from below:
//
// URL: https://www.iana.org/assignments/http-methods/methods.csv
// Last-Modified: 2026-06-18T04:06:22Z

import yExtensions

public enum HTTPMethod: Sendable {
  case acl
  case baselineControl
  case bind
  case checkin
  case checkout
  case connect
  case copy
  case delete
  case get
  case head
  case label
  case link
  case lock
  case merge
  case mkactivity
  case mkcalendar
  case mkcol
  case mkredirectref
  case mkworkspace
  case move
  case options
  case orderpatch
  case patch
  case post
  case pri
  case propfind
  case proppatch
  case put
  case query
  case rebind
  case report
  case search
  case trace
  case unbind
  case uncheckout
  case unlink
  case unlock
  case update
  case updateredirectref
  case versionControl
  case otherMethod(HTTPMethodString)
}

extension HTTPMethod: Equatable {
  public static func ==(lhs: HTTPMethod, rhs: HTTPMethod) -> Bool {
    switch (lhs, rhs) {
    case (.acl, .acl): return true
    case (.baselineControl, .baselineControl): return true
    case (.bind, .bind): return true
    case (.checkin, .checkin): return true
    case (.checkout, .checkout): return true
    case (.connect, .connect): return true
    case (.copy, .copy): return true
    case (.delete, .delete): return true
    case (.get, .get): return true
    case (.head, .head): return true
    case (.label, .label): return true
    case (.link, .link): return true
    case (.lock, .lock): return true
    case (.merge, .merge): return true
    case (.mkactivity, .mkactivity): return true
    case (.mkcalendar, .mkcalendar): return true
    case (.mkcol, .mkcol): return true
    case (.mkredirectref, .mkredirectref): return true
    case (.mkworkspace, .mkworkspace): return true
    case (.move, .move): return true
    case (.options, .options): return true
    case (.orderpatch, .orderpatch): return true
    case (.patch, .patch): return true
    case (.post, .post): return true
    case (.pri, .pri): return true
    case (.propfind, .propfind): return true
    case (.proppatch, .proppatch): return true
    case (.put, .put): return true
    case (.query, .query): return true
    case (.rebind, .rebind): return true
    case (.report, .report): return true
    case (.search, .search): return true
    case (.trace, .trace): return true
    case (.unbind, .unbind): return true
    case (.uncheckout, .uncheckout): return true
    case (.unlink, .unlink): return true
    case (.unlock, .unlock): return true
    case (.update, .update): return true
    case (.updateredirectref, .updateredirectref): return true
    case (.versionControl, .versionControl): return true
    case (.otherMethod(let lstr), .otherMethod(let rstr)): return lstr == rstr
    default: return false
    }
  }
}

extension HTTPMethod: RawRepresentable {
  public typealias RawValue = String

  public var rawValue: String {
    switch self {
    case .acl: return "ACL"
    case .baselineControl: return "BASELINE-CONTROL"
    case .bind: return "BIND"
    case .checkin: return "CHECKIN"
    case .checkout: return "CHECKOUT"
    case .connect: return "CONNECT"
    case .copy: return "COPY"
    case .delete: return "DELETE"
    case .get: return "GET"
    case .head: return "HEAD"
    case .label: return "LABEL"
    case .link: return "LINK"
    case .lock: return "LOCK"
    case .merge: return "MERGE"
    case .mkactivity: return "MKACTIVITY"
    case .mkcalendar: return "MKCALENDAR"
    case .mkcol: return "MKCOL"
    case .mkredirectref: return "MKREDIRECTREF"
    case .mkworkspace: return "MKWORKSPACE"
    case .move: return "MOVE"
    case .options: return "OPTIONS"
    case .orderpatch: return "ORDERPATCH"
    case .patch: return "PATCH"
    case .post: return "POST"
    case .pri: return "PRI"
    case .propfind: return "PROPFIND"
    case .proppatch: return "PROPPATCH"
    case .put: return "PUT"
    case .query: return "QUERY"
    case .rebind: return "REBIND"
    case .report: return "REPORT"
    case .search: return "SEARCH"
    case .trace: return "TRACE"
    case .unbind: return "UNBIND"
    case .uncheckout: return "UNCHECKOUT"
    case .unlink: return "UNLINK"
    case .unlock: return "UNLOCK"
    case .update: return "UPDATE"
    case .updateredirectref: return "UPDATEREDIRECTREF"
    case .versionControl: return "VERSION-CONTROL"
    case .otherMethod(let string): return string.description
    }
  }

  public init?(rawValue: String) {
    if rawValue.isASCIICaseInsensitivelyEqual(to: "ACL") {
      self = .acl; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "BASELINE-CONTROL") {
      self = .baselineControl; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "BIND") {
      self = .bind; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "CHECKIN") {
      self = .checkin; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "CHECKOUT") {
      self = .checkout; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "CONNECT") {
      self = .connect; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "COPY") {
      self = .copy; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "DELETE") {
      self = .delete; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "GET") {
      self = .get; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "HEAD") {
      self = .head; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "LABEL") {
      self = .label; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "LINK") {
      self = .link; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "LOCK") {
      self = .lock; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "MERGE") {
      self = .merge; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "MKACTIVITY") {
      self = .mkactivity; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "MKCALENDAR") {
      self = .mkcalendar; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "MKCOL") {
      self = .mkcol; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "MKREDIRECTREF") {
      self = .mkredirectref; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "MKWORKSPACE") {
      self = .mkworkspace; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "MOVE") {
      self = .move; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "OPTIONS") {
      self = .options; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "ORDERPATCH") {
      self = .orderpatch; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "PATCH") {
      self = .patch; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "POST") {
      self = .post; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "PRI") {
      self = .pri; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "PROPFIND") {
      self = .propfind; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "PROPPATCH") {
      self = .proppatch; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "PUT") {
      self = .put; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "QUERY") {
      self = .query; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "REBIND") {
      self = .rebind; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "REPORT") {
      self = .report; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "SEARCH") {
      self = .search; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "TRACE") {
      self = .trace; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "UNBIND") {
      self = .unbind; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "UNCHECKOUT") {
      self = .uncheckout; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "UNLINK") {
      self = .unlink; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "UNLOCK") {
      self = .unlock; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "UPDATE") {
      self = .update; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "UPDATEREDIRECTREF") {
      self = .updateredirectref; return
    }
    if rawValue.isASCIICaseInsensitivelyEqual(to: "VERSION-CONTROL") {
      self = .versionControl; return
    }
    if let string = HTTPMethodString(rawValue) {
      self = .otherMethod(string); return
    }
    return nil
  }
}
