#if !canImport(ObjectiveC)
import XCTest

extension NetworkGearUpdaterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NetworkGearUpdaterTests = [
        ("test_ContentDispositionValue", test_ContentDispositionValue),
        ("test_HTTPMethod", test_HTTPMethod),
        ("test_HTTPStatusCode", test_HTTPStatusCode),
        ("test_IANARegisteredContentDispositionParameterKey", test_IANARegisteredContentDispositionParameterKey),
        ("test_IANARegisteredHTTPHeaderFieldName", test_IANARegisteredHTTPHeaderFieldName),
        ("test_MIMETypePathExtension", test_MIMETypePathExtension),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NetworkGearUpdaterTests.__allTests__NetworkGearUpdaterTests),
    ]
}
#endif
